# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

blank_issues_enabled: false

contact_links:

  - name: (A hledger.org website issue)
    url: https://github.com/simonmichael/hledger_site/issues
    about: Please use the hledger_site issue tracker

  - name: (A support request)
    url: https://hledger.org/support
    about: Please use chat, mail list or forum

  - name: (A security issue)
    url: https://joyful.com
    about: Please contact Simon directly
