# Create a github release, when a "[0-9]*" tag is pushed (anywhere ?)
#
# https://github.com/actions/create-release - still pretty rough, 20200609

name: release

on:
  push:
    tags: [ '[0-9]*', 'r[0-9]*' ]
    branches: [ 'master', '[0-9]*-branch' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: X.Y
          release_name: X.Y
          body: |
            CHANGE 1; CHANGE 2.
            https://hledger.org/release-notes.html#hledger-X-Y
          draft: true
          prerelease: true
